services:
#================================
#Lancer postgresQl
#================================
  pg-insa:
    container_name: pg-insa
    image: pg-insa:latest
    command: postgres -c 'max_connections=200'
    networks:
      - insa-bridge
    hostname: pg-insa
    restart: always
    ports:
      - "5432:5432"
    environment:
      - TZ=CET
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=insa
      - POSTGRES_HOST_AUTH_METHOD=trust
      # ne pas oublier de parameter le volume de postgresql sur disque lvm
    volumes:
      - ./pgdata:/var/lib/postgresql/data

#================================
#Lancer le service ws template
#================================
  ws-template:
    depends_on:
      - pg-insa
    container_name: ws-template
    image: ws_services_template:latest
    networks:
      - insa-bridge
    hostname: ws-template
    restart: always
    ports:
      - "8800:8800"

#renommer le r√©seau par defaut des services
networks:
    insa-bridge:
      name: insa-bridge
